stages:
  - check
  - build
  - test
  - report
  - sonar

# Job to check if SonarQube server is reachable
check-sonarqube-server:
  stage: check
  image: curlimages/curl:latest
  script:
    - echo "Checking SonarQube server status..."
    - |
      if curl --output /dev/null --silent --head --fail "http://192.168.33.10:9000"; then
        echo "SonarQube server is reachable."
      else
        echo "SonarQube server is not reachable. Exiting."
        exit 1
      fi

# Job to check Java and Maven versions
check-java-maven:
  stage: check
  image: maven:3.8.3-openjdk-17
  script:
    - echo "Checking Java version..."
    - java -version  # Check Java version
    - echo "Checking Maven version..."
    - mvn --version  # Check Maven version

# Job to run Maven build
run-maven-build:
  stage: build
  image: maven:3.8.3-openjdk-17
  script:
    - echo "Running Maven build..."
    - mvn compile  # Compile the project

# Job to run Maven tests
run-maven-tests:
  stage: test
  image: maven:3.8.3-openjdk-17
  script:
    - echo "Running Maven tests..."
    - mvn clean test  # Run tests and clean up the previous builds

# Job to generate JaCoCo coverage report
generate-jacoco-report:
  stage: report
  image: maven:3.8.3-openjdk-17
  script:
    - echo "Generating JaCoCo coverage report..."
    - mvn jacoco:report  # Generate JaCoCo coverage report
  artifacts:
    paths:
      - target/site/jacoco  # Store the JaCoCo report as an artifact

# Job to run SonarQube analysis
sonarqube-analysis:
  stage: sonar
  image: maven:3.8.3-openjdk-17
  script:
    - echo "Running SonarQube analysis..."
    - mvn verify sonar:sonar -Dsonar.projectKey=Devpos_Sonar -Dsonar.host.url=http://192.168.33.10:9000 -Dsonar.login=sqa_d6925384b653b7dc2e4ad63ca0d48b20e408cd3b -X
  only:
    - main
