services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus_auto
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false

  sonarqube:
    image: sonarqube
    container_name: sonarqube_auto
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    environment:
      - SONAR_JDBC_URL=jdbc:mysql://db:3306/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_WEB_JDBC_URL=jdbc:mysql://db:3306/sonar
      - SONAR_WEB_JDBC_USERNAME=sonar
      - SONAR_WEB_JDBC_PASSWORD=sonar
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: sonarqube-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sonar
      MYSQL_USER: sonar
      MYSQL_PASSWORD: sonar
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  nexus-data:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-bundled-plugins:
  mysql-data:
